version: '3.8'

services:
  # PocketBase backend
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: gametrack-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
      - ./pb_migrations:/pb_migrations
    environment:
      - POCKETBASE_ADMIN_EMAIL=sadkidjallel@gmail.com
      - POCKETBASE_ADMIN_PASSWORD=changeme123
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # GameTrack frontend
  gametrack-frontend:
    build: .
    container_name: gametrack-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      pocketbase:
        condition: service_healthy

  # Reverse proxy (optional - for production)
  nginx-proxy:
    image: nginx:alpine
    container_name: gametrack-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gametrack-frontend
      - pocketbase
    profiles:
      - production

volumes:
  pocketbase_data:
    driver: local

networks:
  default:
    name: gametrack-network